version: '3.8'

networks:
  proxy:
    name: proxy
    external: true

services:
  traefik:
    image: traefik:v2.5
    command: traefik --configFile=/etc/traefik/traefik.yml
    labels:
      # The Web UI (enabled by --api.insecure=true)
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`localhost`)"
      - "traefik.http.routers.api.entrypoints=http"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.port=8080"
    ports:
      - "5000:80"
    expose:
      - "8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik:ro
    networks:
      - proxy

  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
    networks:
      - proxy

  nginx:
    image: nginx:latest
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # TODO adicionar o host dinamicamente
      - "traefik.http.routers.nginx.rule=Host(`localhost`) && PathPrefix(`/home`)"
      - "traefik.http.routers.nginx.middlewares=strip-nginx"
      - "traefik.http.middlewares.strip-nginx.stripprefix.prefixes=/home"
    networks:
      - proxy
